{% set name = "jsx-lexer" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5f5270cad47b065417fd7bdb780199d5166bd4a88a2a0fd7412e90e7a59b5cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pygments >=2.1
    - python

test:
  source_files:
    - tests
  imports:
    - jsx
  commands:
    - pip check
    - pytest --cov jsx
  requires:
    - pip
    - pytest
    - pytest-cov

about:
  home: https://pypi.org/project/jsx-lexer
  summary: A JSX lexer for Pygments
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/fcurella/jsx-lexer

extra:
  recipe-maintainers:
    - bollwyvl
