{% set version = "2.0.1" %}

package:
  name: jsx-lexer
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/j/jsx-lexer/jsx-lexer-{{ version }}.tar.gz
    sha256: 0d9aa653e74d7973d74021dde8349896c0df094d8e40349b92b35e0930ed7f71
  - folder: src
    url: https://github.com/fcurella/jsx-lexer/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e07de4b3103eee0fed4accc520dad27faa94eab5e5ef4e901d024d08447f4182

build:
  number: 1
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pygments >=2.12.0
    - python >={{ python_min }}

test:
  source_files:
    - src/tests
  requires:
    - pip
    # many tests fail with later pygments
    - pygments <2.17
    - pytest-cov
    - python {{ python_min }}
  imports:
    - jsx
  commands:
    - pip check
    - cd src/tests
    - coverage run --source=jsx --branch -m pytest -vv --tb=long --color=yes
    - coverage report --show-missing --skip-covered --fail-under=100

about:
  home: https://pypi.org/project/jsx-lexer
  summary: A JSX lexer for Pygments
  license: MIT
  license_file: dist/LICENSE
  dev_url: https://github.com/fcurella/jsx-lexer

extra:
  recipe-maintainers:
    - bollwyvl
