{% set version = "2.0.0" %}

package:
  name: jsx-lexer
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsx-lexer/jsx-lexer-{{ version }}.tar.gz
  sha256: ca22483ced80a92e45fa1855da7cf99309852c0637842a79a759e10ea57b904d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygments >=2.12.0
    - python >=3.6

test:
  source_files:
    - tests
  imports:
    - jsx
  commands:
    - pip check
    - pytest --cov jsx --cov-report term-missing:skip-covered --cov-fail-under 100
  requires:
    - pip
    - pytest
    - pytest-cov

about:
  home: https://pypi.org/project/jsx-lexer
  summary: A JSX lexer for Pygments
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/fcurella/jsx-lexer

extra:
  recipe-maintainers:
    - bollwyvl
